#!/bin/sh
# Using external pipe with st, give a dmenu prompt of recent commands,
# allowing the user to copy the output of one.
# xclip required for this script.
# By Jaywalker and Luke

# Crear un archivo temporal para almacenar la salida
set -x
history -r
history | tail -n 20
tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)
trap 'rm "$tmpfile"' 0 1 15


# Obtener los últimos comandos ejecutados y guardarlos en el archivo temporal
history | tail -n 20 > "$tmpfile"

# Procesar el archivo temporal para obtener el último prompt no vacío
ps1="$(grep "\S" "$tmpfile" | tail -n 1 | sed 's/^\s*//' | cut -d ' ' -f1)"

# Usar dmenu para permitir que el usuario elija un comando del historial
chosen="$(grep -F "$ps1" "$tmpfile" | sed '$ d' | tac | dmenu -p "Copy which command's output?" -i -l 10 | sed 's/[^^]/[&]/g; s/\^/\\^/g')"

# Si se eligió un comando, ejecutarlo y copiar la salida al portapapeles
if [ -n "$chosen" ]; then
    eps1="$(echo "$ps1" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
    # Ejecutar el comando elegido
    output=$(eval "$chosen")
    # Copiar la salida al portapapeles
    echo "$output" | xclip -selection clipboard
fi

