#!/bin/bash
PROJECT=$(ls -d ~/projects/*\/ | dmenu -l 15 -p "project: ")
NODE_MANAGER=$(echo -e "pnpm\nnpm" | dmenu -l 15 -p "package manager: ")
session=$(echo "asd" | dmenu -p "name of the session: ")

cd $PROJECT
tmux new-session -d -s $session
tmux rename-window -t $session client
tmux send-keys -t $session "cd client && clear" ENTER

tmux new-window -t $session
tmux rename-window -t $session server
tmux send-keys -t $session "cd server && clear" ENTER

# initialize client and servers
tmux new-window -t $session
tmux rename-window -t $session client-server
tmux split-window -h -t $session
if $NODE_MANAGER -eq "pnpm"; then
   tmux send-keys -t $session.0 "cd client && $NODE_MANAGER dev" ENTER
   tmux send-keys -t $session.1 "cd server && $NODE_MANAGER dev" ENTER
elif $NODE_MANAGER -eq "npm"; then
   tmux send-keys -t $session.1 "cd server && $NODE_MANAGER dev" ENTER
fi

tmux send-keys -t $session.1 "cd server && pnpm dev" ENTER

tmux a -t $session 



