#!/bin/sh

# Screenshot script with dmenu, maim, xclip, and tesseract OCR.

output="$(date '+%y%m%d-%H%M-%S').png"
xclip_cmd="xclip -sel clip -t image/png"
ocr_cmd="xclip -sel clip"
dunst_cmd='dunstify "📸 Screenshot taken"'

choice=$(printf "a selected area\\ncurrent window\\nfull screen\\na selected area (copy)\\ncurrent window (copy)\\nfull screen (copy)\\ncopy selected image to text" | dmenu -l 7 -i -p "Screenshot which area?")

case "$choice" in
"a selected area")
    maim -u -s "pic-selected-${output}" && eval "$dunst_cmd"
    ;;
"current window")
    maim -B -q -d 0.2 -i "$(xdotool getactivewindow)" "pic-window-${output}" && eval "$dunst_cmd"
    ;;
"full screen")
    maim -q -d 0.2 "pic-full-${output}" && eval "$dunst_cmd"
    ;;
"a selected area (copy)")
    maim -u -s | $xclip_cmd && eval "$dunst_cmd"
    ;;
"current window (copy)")
    maim -q -d 0.2 -i "$(xdotool getactivewindow)" | $xclip_cmd && eval "$dunst_cmd"
    ;;
"full screen (copy)")
    maim -q -d 0.2 | $xclip_cmd && eval "$dunst_cmd"
    ;;
"copy selected image to text")
    tmpfile=$(mktemp /tmp/ocr-XXXXXX.png) &&
        maim -u -s >"$tmpfile" &&
        tesseract "$tmpfile" - -l eng | $ocr_cmd &&
        rm "$tmpfile" &&
        eval "$dunst_cmd"
    ;;
esac
