#!/bin/bash

# slightly scuffed wallpaper picker menu for use with pywal - uses nsxiv if installed, otherwise uses dmenu

FOLDER=~/Images/wallpapers/ # wallpaper folder
SCRIPT=~/scripts/pywal16 # script to run after wal for refreshing programs, etc.


menu () {
	if command -v nsxiv >/dev/null; then 
		CHOICE=$(nsxiv -otb $FOLDER/*)
		MODE=$(echo -e "center\ntile\nscale" | dmenu -l 15)
	else 
		CHOICE=$(echo -e "Random\n$(command ls -v $FOLDER)" | dmenu -l 15 -i -p "Wallpaper: ")
	fi

	
	case $CHOICE in
		Random) feh --bg-center "$FOLDER" ;; # dmenu random option
		*.*)
			
			ESCAPED_CHOICE=$(echo "$CHOICE" | sed 's/\//\\\//g')

			feh --bg-"$MODE" "$CHOICE" && perl -i -pe 's/^exec_always feh --bg-(center|tile|scale|fill|max) .*/exec_always feh --bg-'"$MODE"' "'"$ESCAPED_CHOICE"'"/' ~/.config/i3/config;;

		*) exit 1 ;;
	esac
}

# If given arguments:
# First argument will be used by pywal as wallpaper/dir path
# Second will be used as theme (use wal --theme to view built-in themes)

case "$#" in
		0) menu ;;
		1) wal -i "$1" -o $SCRIPT ;;
		2) wal -i "$1" --theme $2 -o $SCRIPT ;;
		*) exit 0 ;;
esac
