[colors.primary]
background = "#000000"

[window]
opacity = 0.875

# [window.padding]
# x = 20
# y = 5

[font]
# normal = {family = "Gohu GohuFont"}
normal = {family = "CozetteHiDpi"}
# normal = {family = "Greybeard 18px"}
# normal = {family = "edges"}
# normal = {family = "Iosevka Nerd Font"}
# normal = {family = "Hack Nerd Font"}
# normal = {family = "Unifont"}
