[colors.primary]
background = "#000000"

[window]
opacity = 0.95

[window.padding]
x = 20
y = 5

[font]
# normal = {family = "Gohu GohuFont"}
normal = {family = "Greybeard 15px"}
# normal = {family = "Unifont"}

